version: 2.1
jobs:
  deployment:
    machine: true
    resource_class: dukesofhazards/runner
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    working_directory: ~
    steps:
      - checkout
      - run:
          name: build env set access
          environment:
            - SOMEVAR: placeholder
          command: |
            chmod +x ops/*sh && . /etc/profile.d/pyenv-path.sh
            ops/env.sh ${SOMEVAR}
      - run:
          name: deploy Hashicorp Vault
          command: |
            kubectl get nodes
            helm repo add hashicorp https://helm.releases.hashicorp.com

#            sudo docker login -u $DOCKER_USER -p $DOCKER_PASS

workflows:
  version: 2.1
  init_and_deploy:
    jobs:
      - deployment:
          context:
            - deployment-an

